language: python
python:
  - "2.7"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "3.6-dev" # 3.6 development branch
  - "nightly" # currently points to 3.7-dev
install:
    - pip install -r requirements.txt
    - pip install braintree coveralls mock mysqlclient
env:
  - DB=sqlite
  - DB=mgit ysql
  - DB=postgres
addons:
  postgresql: "9.4"
script:
  - coverage run --omit=*/tests/* --source=hc manage.py test
after_success: coveralls
cache: pip